feat: enable whitelisting multiple images
OT-BUILDPIPER-MARKETPLACE/BP-BASE-IMAGE-VALIDATOR pull request #1
Opened 2023-10-12 15:41 UTC by rishabh96b

## Description

Enables multiple base images to be whitelisted. The image names can be set in the env variable using comma separated values. 
```dockerfile
ENV WHITELIST_IMAGE_NAME "alpine,scratch"
```

## Tests
With Dockerfile having single `FROM ..` line:
```log
[10/12/23: 14:54:31] [INFO] I'll do processing at [/home/rishabh/opstree/base-image-validator-proj/fork/BP-BASE-IMAGE-VALIDATOR//]
FROM alpine
RUN apk add --no-cache --upgrade bash
.
.
ENTRYPOINT [ "./build.sh" ]
[10/12/23: 14:54:36] [INFO] Got below lines in Dockerfile [FROM alpine]
[10/12/23: 14:54:36] [INFO] The base image is: alpine
alpine
[10/12/23: 14:54:36] [INFO] Image is whitelisted: alpine
[10/12/23: 14:54:36] [INFO] Congratulations BP_BASE_IMAGE_VALIDATOR succeeded!!!
```

With Dockerfile containting multiple `FROM..` lines or multi-stage Dockerfiles.
```
FROM golang:1.21
WORKDIR /src
..
FROM scratch
..
[10/12/23: 14:57:51] [INFO] Got below lines in Dockerfile [FROM golang:1.21
FROM scratch]
[10/12/23: 14:57:52] [INFO] Image is whitelisted: scratch
[10/12/23: 14:57:52] [INFO] Congratulations BP_BASE_IMAGE_VALIDATOR succeeded!!!
```
## Limitation
If a Dockerfile is using `AS` then this will not be successful.

2023-10-14 15:28 UTC, sandy724 requested changes

2023-10-14 15:28 UTC, sandy724 commented on build.sh
> +while IFS= read -r line; do
This should go in a functoin

2023-10-14 15:28 UTC, sandy724 commented on build.sh
> +while IFS= read -r line; do
getBaseImage
Something like that

2023-10-14 15:28 UTC, sandy724 commented on Dockerfile
> +ENV WHITELIST_IMAGE_NAME "alpine,scratch"
Shall we change it to WHITELIST_IMAGES_NAME

2023-10-16 07:51 UTC, rishabh96b commented on build.sh
> +while IFS= read -r line; do
created a new utility file and added `getBaseImageFromFilteredDockerfile` function, updated in PR: https://github.com/OT-BUILDPIPER-MARKETPLACE/BP-BASE-SHELL-STEPS/pull/17/files
Will push changes respective of this repo also.

2023-10-18 01:27 UTC, sandy724 approved these changes
LGTM, assuming you have tested it

2023-10-18 01:28 UTC, merged